version: 2.0
jobs:
  build:
    docker:
      - image: openjdk:8
        environment:
          LEIN_FAST_TRAMPOLINE: yes
          LEIN_ROOT: nbd
    working_directory: ~/clojars
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: bin/lein deps
      - save_cache:
          paths:
            - $HOME/.m2
            - $HOME/.lein
          key: << checksum "project.clj" >>
      - run: bin/lein do run -m user/migrate, test, uberjar
      - run: mv target/uberjar/clojars-web-*-standalone.jar clojars-uberjar.jar
      - store_artifacts:
          path: clojars-uberjar.jar
          destination: uberjar
